# Generated by Django 4.2.7 on 2023-11-17 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(default=uuid.uuid4, editable=False, max_length=10000)),
                ('Rooms_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookingname', models.CharField(max_length=1000)),
                ('Starting_Time', models.DateTimeField()),
                ('Ending_Time', models.DateTimeField()),
                ('Purpose_of_meeting', models.CharField(blank=True, max_length=1000, null=True)),
                ('Booking_Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterroom.masterroom')),
            ],
        ),
    ]
